### ISSUE TITLE
Incompatible maui handler

### ISSUE THREAD

**Issue by developer9969** [jsuarezruiz/TemplateMAUI#2]
Hi
Thanks for these controls - just run your solution in Version 17.3.0 Preview 1.1 against my android emulator android 12
any item I click I get - this happens for all controls in this solution. Am I missing something?

Many thanks

![image](https://user-images.githubusercontent.com/16970109/170422130-b3db512b-41f1-49d1-8ede-36262d0d2b47.png)

**Comment by jsuarezruiz** [comment]
Yes, this library is not ready yet because we are waiting this https://github.com/jsuarezruiz/TemplateMAUI/issues/1 to be fixed.
Ideally will be fixed on .NET MAUI, if could not happen for the next release will register in the library the necessary to get it working.

Thanks for the interesting, we will have progress soon.
